# Generated by Django 3.1.6 on 2021-03-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20210226_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='back_picture',
            field=models.ImageField(blank='True', null='True', upload_to='book_covers'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='offer',
            name='front_picture',
            field=models.ImageField(blank='True', null='True', upload_to='book_covers'),
            preserve_default='True',
        ),
    ]
