# Generated by Django 3.1.6 on 2021-03-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20210301_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='back_picture',
            field=models.ImageField(default=1, upload_to='book_covers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='front_picture',
            field=models.ImageField(default=1, upload_to='book_covers'),
            preserve_default=False,
        ),
    ]
