# Generated by Django 3.1.6 on 2021-03-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20210301_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='back_picture',
            field=models.ImageField(blank=True, default=None, null='True', upload_to='book_covers'),
        ),
    ]
