# Generated by Django 3.1.6 on 2021-03-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='genre',
            field=models.CharField(blank='False', max_length=10),
        ),
    ]
