# Generated by Django 3.1.6 on 2021-03-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_offer_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='location',
        ),
    ]
