# Generated by Django 3.1.6 on 2021-03-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_remove_offer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='genre',
            field=models.CharField(choices=[('scifi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('action', 'Action'), ('comic', 'Comic'), ('historical', 'Historical'), ('adventure', 'Adventure'), ('romance', 'Romance'), ('horror', 'Horror'), ('biography', 'Biography'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(),
        ),
    ]
