# Generated by Django 3.1.6 on 2021-03-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_auto_20210303_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='id_buer',
            new_name='id_buyer',
        ),
    ]
