# Generated by Django 3.1.6 on 2021-03-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_auto_20210303_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='back_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='book_covers'),
        ),
    ]
