# Generated by Django 3.1.6 on 2021-03-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pending',
            old_name='status',
            new_name='sold',
        ),
    ]
