# Generated by Django 3.1.6 on 2021-03-18 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0013_auto_20210318_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='id_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='selling_user', to='users.user'),
            preserve_default=False,
        ),
    ]
