# Generated by Django 3.1.6 on 2021-03-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_pending_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending',
            name='sold',
        ),
    ]
