# Generated by Django 3.1.6 on 2021-03-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_remove_pending_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='back_picture',
        ),
    ]
